adb pull sdcard/Pictures/testImages/results/Abilify.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Acamprosate.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Acetaminophen.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Acetaminophen_500mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Acetaminophen_caffeine.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Acyclovir.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Advil.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Advil_2_color.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Alendronate.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Alprazolam_2mg_quarter.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Amiloride.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Amlodipine.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Amlodipine_5mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Amlodipine_Valsartan.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Azasan.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Buspirone.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Buspirone_5mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Campral.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Cimetidine.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Cordarone.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Coreg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Daklinza.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/DDAVP.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Dexmethylphenidate.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Diflucan.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Doryx.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Estazolam.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Etidronate_Disodium.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Etodolac.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Exemestane.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Famotidine.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Fanapt.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/FerraPlus.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Fluconazole.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Fluconazole_100mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Fosinopril.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Glipizide_hole.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Glyburide_Micronized.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Glyxambi.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Gralise.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Imuran.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Irbesartan.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Klonopin_hole.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamictal.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamictal_shield.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamictal_XR.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamictal_XR_tall.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamotrigine.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamotrigine_halves.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamotrigine_thick.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lamotrigine-1.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Lasix.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Levoxyl.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Norel_AD.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Norvasc.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Norvasc_5mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Nuvigil.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Otezla.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Pepcid.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Plaquenil.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Prinivil.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Prinivil_10mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Propecia.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Proscar.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Rolaids.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Saphris.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Spritam.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Symax_Duotab.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Tenex.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Tiumeq.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Tranxene.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Tylenol_500mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Uloric.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Valium_hole.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Vaseretic.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Vasotec.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Xanax_1mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Xanax_1mg_cut.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Xanax_2mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Xanax_2mg_cut.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Xanax_3mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Xanax_5mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Zebeta_5mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Zebeta_10mg.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Ziagen.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Zovirax.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Zubsolv.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Zydone.jpg ..\..\pics\testResults
adb pull sdcard/Pictures/testImages/results/Zytiga.jpg ..\..\pics\testResults
