adb pull sdcard/Pictures/1a-Original.jpg ..\..\pics
adb pull sdcard/Pictures/1b-Undistorted.jpg ..\..\pics
adb pull sdcard/Pictures/1c-Removal.jpg ..\..\pics
adb pull sdcard/Pictures/3-Cleaned.jpg ..\..\pics
adb pull sdcard/Pictures/4a-Canny.jpg ..\..\pics
adb pull sdcard/Pictures/4b-Edge.jpg ..\..\pics
adb pull sdcard/Pictures/5a-Inverse.jpg ..\..\pics
adb pull sdcard/Pictures/5b-Blob.jpg ..\..\pics
adb pull sdcard/Pictures/6-Final.jpg ..\..\pics
adb pull sdcard/Pictures/7-Calibration.jpg ..\..\pics
