adb pull sdcard/Pictures/template-100.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-099.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-098.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-097.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-096.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-095.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-094.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-093.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-092.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-091.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-090.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-085.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-080.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-075.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-070.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-065.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-060.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-055.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-050.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-045.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-040.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-035.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-030.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-025.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-020.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-015.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-010.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-005.jpg ..\..\pics\Templates
adb pull sdcard/Pictures/template-000.jpg ..\..\pics\Templates
