adb shell mkdir -p sdcard/Pictures/testImages/results
adb push .\testImages\Mask1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Mask2.jpg sdcard/Pictures/testImages/
adb push .\testImages\Mask3bottom.jpg sdcard/Pictures/testImages/
adb push .\testImages\EmptyBin.jpg sdcard/Pictures/testImages/
adb push .\testImages\Abilify.jpg sdcard/Pictures/testImages/
adb push .\testImages\Abilify_Edge1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Abilify_Thresh1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acamprosate.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acetaminophen.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acetaminophen_500mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acetaminophen_500mg_Edge1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acetaminophen_500mg_Thresh1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acetaminophen_caffeine.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acyclovir.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acyclovir_Edge1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Acyclovir_Thresh1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Advil.jpg sdcard/Pictures/testImages/
adb push .\testImages\Advil_2_color.jpg sdcard/Pictures/testImages/
adb push .\testImages\Alendronate.jpg sdcard/Pictures/testImages/
adb push .\testImages\Alprazolam_2mg_quarter.jpg sdcard/Pictures/testImages/
adb push .\testImages\Amiloride.jpg sdcard/Pictures/testImages/
adb push .\testImages\Amlodipine.jpg sdcard/Pictures/testImages/
adb push .\testImages\Amlodipine_5mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Amlodipine_Valsartan.jpg sdcard/Pictures/testImages/
adb push .\testImages\Azasan.jpg sdcard/Pictures/testImages/
adb push .\testImages\Buspirone.jpg sdcard/Pictures/testImages/
adb push .\testImages\Buspirone_5mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Campral.jpg sdcard/Pictures/testImages/
adb push .\testImages\Cimetidine.jpg sdcard/Pictures/testImages/
adb push .\testImages\Cordarone.jpg sdcard/Pictures/testImages/
adb push .\testImages\Coreg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Daklinza.jpg sdcard/Pictures/testImages/
adb push .\testImages\DDAVP.jpg sdcard/Pictures/testImages/
adb push .\testImages\Dexmethylphenidate.jpg sdcard/Pictures/testImages/
adb push .\testImages\Diflucan.jpg sdcard/Pictures/testImages/
adb push .\testImages\Doryx.jpg sdcard/Pictures/testImages/
adb push .\testImages\Estazolam.jpg sdcard/Pictures/testImages/
adb push .\testImages\Etidronate_Disodium.jpg sdcard/Pictures/testImages/
adb push .\testImages\Etodolac.jpg sdcard/Pictures/testImages/
adb push .\testImages\Exemestane.jpg sdcard/Pictures/testImages/
adb push .\testImages\Famotidine.jpg sdcard/Pictures/testImages/
adb push .\testImages\Fanapt.jpg sdcard/Pictures/testImages/
adb push .\testImages\FerraPlus.jpg sdcard/Pictures/testImages/
adb push .\testImages\Fluconazole.jpg sdcard/Pictures/testImages/
adb push .\testImages\Fluconazole_100mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Fosinopril.jpg sdcard/Pictures/testImages/
adb push .\testImages\Glipizide_hole.jpg sdcard/Pictures/testImages/
adb push .\testImages\Glyburide_Micronized.jpg sdcard/Pictures/testImages/
adb push .\testImages\Glyxambi.jpg sdcard/Pictures/testImages/
adb push .\testImages\Gralise.jpg sdcard/Pictures/testImages/
adb push .\testImages\Imuran.jpg sdcard/Pictures/testImages/
adb push .\testImages\Irbesartan.jpg sdcard/Pictures/testImages/
adb push .\testImages\Klonopin_hole.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamictal.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamictal_shield.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamictal_XR.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamictal_XR_tall.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamotrigine.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamotrigine_halves.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamotrigine_thick.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lamotrigine-1.jpg sdcard/Pictures/testImages/
adb push .\testImages\Lasix.jpg sdcard/Pictures/testImages/
adb push .\testImages\Levoxyl.jpg sdcard/Pictures/testImages/
adb push .\testImages\Norel_AD.jpg sdcard/Pictures/testImages/
adb push .\testImages\Norvasc.jpg sdcard/Pictures/testImages/
adb push .\testImages\Norvasc_5mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Nuvigil.jpg sdcard/Pictures/testImages/
adb push .\testImages\Otezla.jpg sdcard/Pictures/testImages/
adb push .\testImages\Pepcid.jpg sdcard/Pictures/testImages/
adb push .\testImages\Plaquenil.jpg sdcard/Pictures/testImages/
adb push .\testImages\Prinivil.jpg sdcard/Pictures/testImages/
adb push .\testImages\Prinivil_10mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Propecia.jpg sdcard/Pictures/testImages/
adb push .\testImages\Proscar.jpg sdcard/Pictures/testImages/
adb push .\testImages\Rolaids.jpg sdcard/Pictures/testImages/
adb push .\testImages\Saphris.jpg sdcard/Pictures/testImages/
adb push .\testImages\Spritam.jpg sdcard/Pictures/testImages/
adb push .\testImages\Symax_Duotab.jpg sdcard/Pictures/testImages/
adb push .\testImages\Tenex.jpg sdcard/Pictures/testImages/
adb push .\testImages\Tiumeq.jpg sdcard/Pictures/testImages/
adb push .\testImages\Tranxene.jpg sdcard/Pictures/testImages/
adb push .\testImages\Tylenol_500mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Uloric.jpg sdcard/Pictures/testImages/
adb push .\testImages\Valium_hole.jpg sdcard/Pictures/testImages/
adb push .\testImages\Vaseretic.jpg sdcard/Pictures/testImages/
adb push .\testImages\Vasotec.jpg sdcard/Pictures/testImages/
adb push .\testImages\Xanax_1mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Xanax_1mg_cut.jpg sdcard/Pictures/testImages/
adb push .\testImages\Xanax_2mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Xanax_2mg_cut.jpg sdcard/Pictures/testImages/
adb push .\testImages\Xanax_3mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Xanax_5mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Zebeta_5mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Zebeta_10mg.jpg sdcard/Pictures/testImages/
adb push .\testImages\Ziagen.jpg sdcard/Pictures/testImages/
adb push .\testImages\Zovirax.jpg sdcard/Pictures/testImages/
adb push .\testImages\Zubsolv.jpg sdcard/Pictures/testImages/
adb push .\testImages\Zydone.jpg sdcard/Pictures/testImages/
adb push .\testImages\Zytiga.jpg sdcard/Pictures/testImages/
